name:          "WTF, HTML and CSS?"
url:           https://wtf-html-css.std.community
repo:          https://github.com/thestd/wtf-html-css
std-link:      https://github.com/thestd/
twitter:       https://twitter.com/mdo

markdown:      redcarpet
permalink:     pretty
highlighter:   rouge
